execute pathogen#infect()
syntax on
filetype plugin indent on

syntax enable
set background=dark
colorscheme solarized

set nu
set tabstop=2
set shiftwidth=0

set mouse=a

set formatoptions-=cro

filetype plugin on

set wildmode=longest,list,full
set wildmenu

" set foldmethod=syntax
